### ISSUE TITLE
Fails to error if SQL does not specify project name

### ISSUE THREAD

**Issue by Marty08** [servian/bigquery-view-analyzer#20]
When applying 
```bqva authorize --view "analytics-sandbox-temp:analytical_views.view_1"```
The underlying view does not specify the project name in the query :
e.g ```select * from dataset.table```

BQVA cli response is:
Applying nested authorized view permissions for view 'analytics-sandbox-tem
analytics-sandbox-temp:analytical_views.view_1 

The permissions are not applied but BQVA implies the permissions were granted. Also when applying tree to the same query, BQVA does not recognise anything above the view speciifed

```bqva tree --status --view "analytics-sandbox-temp:analytical_views.view_1"
⠋ Fetching dependency tree for view 'analytics-sandbox-temp:analytical_views.
Key:
◉ = Project  ◉ = Table
◉ = Dataset  ◉ = View

analytics-sandbox-temp:analytical_views.view_1```

**Comment by christippett** [comment]
Hey @Marty08. Given the project is omitted from the view SQL, do we assume the view belongs to the same project as the view (analytics-sandbox-temp)?

**Comment by Marty08** [comment]
Good point.

I suppose if the project is not specified in the SQL, the view would fail as it wouldn't find the table from another project; however, if you have multiple projects with the same dataset and table, it could cause issues by authorising the wrong tables.

I've fixed the issue by specifying the project, but would be good for a "no project specified for dataset.name" exception to be thrown if there is no project specified in the SQL, as it took me a few minutes to figure out why it was happening.

**Comment by christippett** [comment]
Agreed. This scenario would make for a good test case... something this project sorely needs at this point! When I next have some downtime I'll look to strengthen our test coverage so we catch these types of silent failures early.
