### ISSUE TITLE
Feature Request: Run for multiple views and/or on all views in a dataset

### ISSUE THREAD

**Issue by B0yc3y** [servian/bigquery-view-analyzer#3]
The ability to provide a list of views as an input or a dataset containing multiple views, and be prompted to approve something like the `git add -p` command allows you to would be really useful for quick resolution of view auth issues on multiple views.

Something like:

`bqva tree --status -v -d "project-1:my_cool_dataset-123456"`

and/or

`bqva tree --status -v -d "project-1:my_cool_dataset-123456.my_view_1,project-1:my_cool_dataset-123456.my_view_2",project-2:my_cool_dataset-123456.my_view_3`

Could be then programmatically added to a pipeline when new views are checked into a repo.

**Comment by Marty08** [comment]
B0yc3y, you could just write it into a loop.

**Comment by christippett** [comment]
Closing this, as @Marty08 makes a good point about importing this library in your own code to loop through multiple views.

@Marty08, I know you've already applied this technique. I'd welcome a pull request from you to update the README documenting how you've implemented this.

**Comment by Marty08** [comment]
Happy to update it, but literally just found a bug in my code.

Partitioned tables aren't  reckognised as tables or views, so need to handle that exception before updating the docs
