### ISSUE TITLE
Commented out lines are not ignored

### ISSUE THREAD

**Issue by matletix** [servian/bigquery-view-analyzer#7]
When the view reference views/tables in lines that are commented out (starting with -- or #), the script still picks up the views/tables in the dependence tree.

**Comment by matletix** [comment]
Ideally, the script should be able to discard the commented out parts in the query, by discarding everything on each line after the "--" or "#" symbols, at the beginning (or not) of the lines, without catching the cases where these symbols are used in a regex or non-commenting way.

**Comment by christippett** [comment]
@matletix, sorry for addressing this so late. We're working on a fix for ignoring commented out table/view references and should have this ready in the next few days.
